# 1. Cấu hình kết nối đến PostgreSQL trong Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/coffee_ecommerce_db
spring.datasource.username=phong_coffee
spring.datasource.password=phong_coffee
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Cấu hình Hibernate tự động tạo/cập nhật bảng dữ liệu vào Postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.address=0.0.0.0
